# Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0, 5.0, 4.0]]) #you can write it without .0's
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Dimension
a.ndim

1

In [5]:
b.shape 

(2, 3)

In [6]:
a.dtype 

dtype('int32')

In [7]:
a.itemsize

4

In [8]:
# Total Size
a.nbytes

12

# Accessing and Changing specific elements, rows, columns, etc

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# (row, columns)
a.shape

(2, 7)

In [11]:
a[1, 5]

13

In [12]:
# Specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Specific column 
a[:, 2] #2.one in both of them


array([ 3, 10])

In [14]:
a[0, 1:-1:2] 
#start at 1, go to the end, stepsize 2, -1 means dont include the last element

array([2, 4, 6])

In [15]:
a[1,5] = 20
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


# Initializing Arrays

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((3,4),dtype='int32') # int32 removes the .0's

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
# Other numbers
np.full((2,2), 99,dtype="float32") 
# Use float64 when high precision is required
# Use float32 when memory efficiency and speed are more important

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [19]:
# Random decimal numbers
np.random.rand(4,2,3) # # 4 matrices, each 2x3

array([[[2.54524331e-01, 6.17889278e-01, 4.59162742e-01],
        [6.85124973e-01, 2.78061656e-01, 3.03666803e-01]],

       [[2.81894599e-04, 4.41121758e-01, 7.81470138e-02],
        [9.95652813e-01, 7.47067769e-01, 1.08568033e-01]],

       [[5.51236280e-01, 6.97418148e-01, 5.45968035e-01],
        [1.74432290e-01, 5.98258345e-01, 9.26511482e-01]],

       [[3.20700830e-01, 6.90413874e-01, 5.80454833e-01],
        [7.04124491e-02, 8.95634743e-01, 9.07123415e-01]]])

In [20]:
# the identity matrix
np.identity(5) # 5x5 matrix 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
ar = np.array([[1,2,3],[4,5,6]])
r1 = np.repeat(ar,3, axis=0) # repeat each row 3 times
print(r1) 

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [ ]:
ar = np.array([[1,2,3],[4,5,6]]) # dont forget to write it again 
r2 = np.repeat(ar,3, axis=1) # repeat each column 3 times
print(r2)

[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

In [ ]:
import numpy as np

matrix = np.ones((5, 5), dtype=int)
matrix[1, 1:4] = 0 # sets row 1, columns 1, 2, 3 to 0
matrix[2, 1] = 0 # Sets row 2, column 1 to 0
matrix[2, 3] = 0 # Sets row 2, column 3 to 0
matrix[2, 2] = 9 # Sets row 2, column 2 to 9
matrix[3, 1:4] = 0 # sets row 3, columns 1, 2, 3 to 0

print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [43]:
# other version
x = np.ones((5, 5), dtype=int)
y = np.zeros((3, 3), dtype=int)
y[1,1] = 9
x[1:4, 1:4] = y 
print(x)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [59]:
a = np.array([[1,2,3,4,5]])
a + 2

array([[3, 4, 5, 6, 7]])

In [60]:
a - 3

array([[-2, -1,  0,  1,  2]])

In [61]:
b = np.array([[1,4,2,6,7]])
a + b 

array([[ 2,  6,  5, 10, 12]])

In [62]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427]])

# Linear Algebra

In [71]:
a = np.ones((2,3))
b = np.full((3,2), 2)
print(a)
print(b)
np.matmul(a, b) # 1*2 + 1*2 + 1*2

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [73]:
c = np.identity(3)
np.linalg.det(c) # determinant of c

1.0

# Statics

In [75]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats) # minimum value in the array

1

In [ ]:
np.max(stats, axis = 1) # maximum value in each row

array([3, 6])

In [82]:
np.sum(stats, axis = 0) # 1+4, 2+5, 3+6     

array([5, 7, 9])

# Reorganizing Arrays

In [89]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [91]:
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
np.hstack([h1, h2])  # horizontal stack of arrays

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [127]:
datafile =np.genfromtxt("data.txt", delimiter =",")  # Load data from a text file
datafile.astype("int32")

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [128]:
datafile[datafile > 50].astype("int32")

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [129]:
((datafile > 50) & (datafile < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [130]:
True_count = np.count_nonzero((datafile > 50) & (datafile < 100))
print(True_count)
false_count = np.count_nonzero(~((datafile > 50) & (datafile < 100)))
print(false_count)

6
48


In [152]:
m = np.arange(1, 31).reshape((6, 5))
print(m)
m[2:4, 0:2] # rows 2 and 3, columns 0 and 1


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


array([[11, 12],
       [16, 17]])

In [153]:
m[[0,1,2,3] , [1,2,3,4]]

array([ 2,  8, 14, 20])

In [ ]:
m[[0, 4, 5], 3:5] # 3:5 means 3 and 4


array([[ 4,  5],
       [24, 25],
       [29, 30]])